### ISSUE TITLE
Upon schema upload failure provide hint what went wrong

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#865] opened 2019-09-03 11:31 UTC
## Background
When one tries to upload  a schema and it fails, following message appears: _Failed to get the detail of the Schema. Please wait a moment and try reloading the application_
That doesn't really help the user to figure out, what's wrong.

## Feature
Provide some information what went wrong and where in the uploaded file.

**Comment by GeorgiChochov** [comment] 2019-09-03 12:29
Duplicate of #777

**Closed by GeorgiChochov** 2019-09-03 12:29 UTC
Labels: Menas, UX, feature, priority: undecided, request, under discussion

**Comment by benedeki** [comment] 2019-09-03 12:31
Duplicate of recently closed #777. Closing
