### ISSUE TITLE
Short Data Type Standardises Incorrectly to String Type 

### ISSUE THREAD

**Issue by anitadsalves** [AbsaOSS/enceladus#113] opened 2019-01-11 09:07 UTC
Currently, Menas accepts short type as a valid data type but when a dataset goes through standardisation attributes of short type get standardised incorrectly to string type. 
There is no error generated even though this standardisation is technically incorrect. 

Example: 
Menas Schema 
attribute 1: string 
attribute 2: int 
attribute 3: short

Hadoop Raw Schema 
attribute 1: string 
attribute 2: string 
attribute 3: string

Hadoop Post Standardisation Schema
attribute 1: string [correct]
attribute 2: int      [correct]
attribute 3: string [incorrect]

**Comment by GeorgiChochov** [comment] 2019-07-12 13:18
@benedeki Can you please verify this behaviour?

**Comment by benedeki** [comment] 2019-07-22 13:40
Can't reproduce. @anitadsalves  is this observed still on any of the _1.0.0-RC__ versions?

**Comment by GeorgiChochov** [comment] 2019-07-22 14:03
Thanks @benedeki !

@aaishaosman, could you also double check with users and @anitadsalves where and how this was observed? And if we can consider this resolved?

**Comment by benedeki** [comment] 2020-01-30 09:22
Closing, as unable to reproduce and no feed-back, that it's still valid.

**Closed by benedeki** 2020-01-30 09:22 UTC
Labels: Standardization, bug, priority: high
