### ISSUE TITLE
Identify diverged columns in the comparison job

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#135] opened 2019-01-25 10:55 UTC
Based on the feedback of using the Comparison jobs, it would increase productivity if the Comparison Job hints in which exactly columns the rows differ. The challenging part here is to pair distinct rows between the two datasets. Now, the explicitly specified keys (columns to be treated as unique row ids) can be used to join the two datasets. As both datasets have the same schema, we can compare records in each column between the two joined rows.

**Comment by GeorgiChochov** [comment] 2019-01-28 07:59
Closing this as a duplicate of #137

**Closed by GeorgiChochov** 2019-01-28 07:59 UTC
Labels: duplicate, feature, request, tests
