### ISSUE TITLE
Decrease the size of the build log - module Dao

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#722] opened 2019-07-30 10:45 UTC
Decrease the size of the build log by eliminating warnings and other clutter generated from module _Dao_.

**Comment by GeorgiChochov** [comment] 2019-08-05 07:20
Isn't this a duplicate of the already finished #743?

**Comment by GeorgiChochov** [comment] 2019-08-23 06:32
Closing as duplicate of #743

**Closed by GeorgiChochov** 2019-08-23 06:32 UTC
Labels: duplicate, priority: low, refactoring
