### ISSUE TITLE
Menas - JWT cookie not removed when logout performed

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/enceladus#2130] opened 2022-09-15 12:18 UTC
## Describe the bug
When user perform Logout then JWT cookie persist in browser.
When page refresh happen then user can see main page again without login action.
The visible page is without data and not usable.

## To Reproduce
Steps to reproduce the behavior OR commands run:
Expectation:
- No JWT cookie is present.
- Menas DB is not empty.

1. User does login (JWT cookie persisted)
2. User sees main page with Totals with non zero tiles.
3. User does Logout (JWT cookie still persisted)
4. User sees Login page
5. User refreshes the page
6. User sees main page with Totals with zero tiles.

## Expected behavior
After user Logout the JWT cookie does not exist.

## Screenshots
Application state after refresh.
![Application state after refresh.](https://user-images.githubusercontent.com/109138042/190399524-ad95fc74-6e10-4cba-97ab-81a9f1ed11da.png)

## Desktop (please complete the following information):
 - Observed on browsers: Brave 1.43.93, Chrome 103.0.5060.114 , Edge 105.0.1343.33
 - Observed on Windows 10

**Comment by jakipatryk** [comment] 2022-09-16 08:13
Which branch is it on? I'm unable to reproduce, when I do logout and refresh it says "Session has expired" and I'm being redirected to login page.

**Comment by miroslavpojer** [comment] 2022-09-16 08:28
> Which branch is it on? I'm unable to reproduce, when I do logout and refresh it says "Session has expired" and I'm being redirected to login page.

An issue has been found develop branch.

**Comment by jakipatryk** [comment] 2022-09-16 09:48
On develop it works for me.

System: MacOS 12.5.1
Tomcat: 9.0.65
Browser: Chrome 105.0.5195.102

**Comment by jakipatryk** [comment] 2022-11-01 09:06
With #2142 merged this should be fixed (as it removes JWT from cookies totally).

**Comment by miroslavpojer** [comment] 2022-11-01 09:49
> With #2142 merged this should be fixed (as it removes JWT from cookies totally).

I will re-test it.

**Closed** 2022-11-08 12:13 UTC
Labels: bug, Menas, priority: low
